//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WAPS08.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DBMVCSCEntities : DbContext
    {
        public DBMVCSCEntities()
            : base("name=DBMVCSCEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<mStatu> mStatus { get; set; }
        public virtual DbSet<USER> USERS { get; set; }
        public virtual DbSet<AUTO> AUTOS { get; set; }
        public virtual DbSet<VHESTATU> VHESTATUS { get; set; }
    }
}
